version: '3'

services:
  task-app:
    container_name: task-app
    build:
      context: .
    command: bash -c "/app/entrypoint.sh"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  redis:
    image: redis:latest
    ports:
      - "6379:6379"